# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  cp:
      - git commit -a -m "Update"
      - git push
  i:
    cmds:
      - echo "Install"
    silent: true
