# https://taskfile.dev

version: '3'

vars:
  GREETING: Testing django-mongodb with go-task!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - git commit -a -m "Update"
      - git push
    silent: true
  e:
    cmds:
      - echo "Edit"
      - nvim Taskfile.yml
    silent: true
  i:
    cmds:
      - echo "Install"
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -r src/django/tests/requirements/py3.txt
      - cp mongodb_settings.py src/django/tests/mongodb_settings.py
    silent: true
  t:
    cmds:
      - echo "Test"
      - python src/django/tests/runtests.py --settings mongodb_settings -v 2
          aggregation
          aggregation_regress
          annotations
          auth_tests.test_models.UserManagerTestCase
          backends
          basic
          bulk_create
          dates
          datetimes
          db_functions
          delete
          delete_regress
          empty
          expressions
          expressions_case
          defer
          defer_regress
          from_db_value
          introspection
          known_related_objects
          lookup
          m2m_and_m2o
          m2m_intermediary
          m2m_multiple
          m2m_recursive
          m2m_regress
          m2m_signals
          m2m_through
          m2m_through_regress
          m2o_recursive
          many_to_many
          many_to_one
          many_to_one_null
          migrations.test_operations
          model_fields
          model_forms
          mutually_referential
          nested_foreign_keys
          null_fk
          null_fk_ordering
          null_queries
          one_to_one
          ordering
          or_lookups
          queries
          schema
          select_related
          select_related_onetoone
          select_related_regress
          sessions_tests
          timezones
          update
          xor_lookups
