# https://taskfile.dev

version: '3'

vars:
  GREETING: Testing django-mongodb with go-task!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - git commit -a -m "Update"
      - git push
    silent: true
  i:
    cmds:
      - echo "Install"
      - pip install -r requirements.txt
    silent: true
  e:
    cmds:
      - echo "Edit"
      - nvim Taskfile.yml
    silent: true
